### ISSUE TITLE
workspace sort only works if you keep your workspace file in just the right place

### ISSUE THREAD

**Issue by mattgen88** [iciclesoft/workspacesort-for-VSCode#1]
In the function getWorkspacePath, the assumption is made that the workspace json file is in a specific place.

https://github.com/iciclesoft/workspacesort-for-VSCode/blob/master/extension.js#L15

I actually have all my workspace files in ~/workspaces/. none of my repos are there (they're all in golang subdirectories). Not all my repos in a workspace share a common root either. The result is that workspacesort cannot sort my workspace file. 

I don't know much about the API for vscode, but there seems to be a bad assumption to the location of the workespace file.

**Comment by iciclesoft** [comment]
Hi @mattgen88 - Thanks for your bugreport. You are right about how the getWorkspacePath function works. The problem is that the VSCode API does not provide the path to the .code-workspace file. Instead the extension assumes that all top-level folders are in the same directory as this file, which is incorrect. I will have a look at it, but it might not be as easy as it sounds due to the lack of information the API is giving in this regard.

What might help me though is if you provide me with the content of your .code-workspace file, as I might have to go for a solution directly targetted on your situation.

**Comment by iciclesoft** [comment]
@mattgen88 I've created a fix for the problem. When trying to find the .code-workspace file it now traverses the complete filetree based on the folders that are added to the workspace. In addition to that, I've added the setting workspacesort.workspaceDirectory where you can set the absolute path to the directory that contains the .code-workspace file. This setting is only needed when it can't find it automatically.

**Comment by mattgen88** [comment]
This works wonderfully, thanks for helping my sanity!

**Comment by iciclesoft** [comment]
Perfect! I'm glad you like it!

**Comment by fabiobusnellosilvershark** [comment]
I know that this problem seems solved but in my case this error is appearing. What should I do?

"The .code-workspace file for this workspace was not found. Please use the setting workspacesort.workspaceDirectory to tell WorkspaceSort where it can be found."

**Comment by iciclesoft** [comment]
- Go to File > Preferences > Settings
- Click on the tab 'Workspace Settings'
- In 'Search Settings' type 'WorkspaceSort'. It will show you the Workspace Directory setting
- Click 'Edit in settings.json'
- On the right-hand side you see a json-file, containing a settings-object
- Go ahead and type `workspacesort.workspaceDirectory` within the curly braces and hit [Enter]
- Now it will show `"workspacesort.workspaceDirectory": null`, change the `null` to a `string`, which is a path to your `.code-workspace` file, I.E. `"C:/Repos/GIT/MyProject/my-project.code-workspace"`

When you're done, you should have something like the following:
![workspacesettings](https://user-images.githubusercontent.com/7295446/49666696-27b4e500-fa59-11e8-8ebd-bd80593aeeab.png)

Make sure that the value points to the right `.code-workspace` file or one of the parent-directories as it will try to search from there, going down the directory-tree. Please let me know if this helped.
