### ISSUE TITLE
Feature Request: automatic sorting

### ISSUE THREAD

**Issue by fharper** [iciclesoft/workspacesort-for-VSCode#11]
First, thanks for the extension, love it!

Lazy me would love to have the sort trigger when I add a new folder to my workspace.

**Comment by iciclesoft** [comment]
Hi @fharper, in the end lazy programmers are the best programmers :) Let me see what I can do

**Comment by iciclesoft** [comment]
Version 1.6.0 has been published which contains automatic sorting whenever workspace-folders are added.

**Comment by fharper** [comment]
That is amazing! I created the issue since I didn't have time to do a PR for now, and you were super fast to add this feature. Thanks a lot @iciclesoft !

**Comment by iciclesoft** [comment]
My pleasure, the feature has been in the back of my head for quite some time now, seeing this feature request was the final push for me to actually implement it haha.
