### ISSUE TITLE
Running the contributed command:'extension.sort' failed.

### ISSUE THREAD

**Issue by fharper** [iciclesoft/workspacesort-for-VSCode#2]
Using version 1.3.0 of your extension with Visual Studio Code 1.30.1 on macOS, I got the `Running the contributed command:'extension.sort' failed.` error, even if I set the `workspacesort.workspaceDirectory`. Any idea what is happening?

**Comment by iciclesoft** [comment]
All unit- and integration-tests are working as expected on Windows using VSCode 1.30.1. Could you give me some more information about your folder-structure, the value of your `workspacesort.workspaceDirectory` and perhaps even the content of your `.code-workspace` file?

**Comment by fharper** [comment]
Here is my `workspacesort.workspaceDirectory`:

`~/Documents/Code/vscode.code-workspace`

and the content of my file `.code-workspace` file:

```
{
	"folders": [
		{
			"path": "OOCZ"
		},
		{
			"path": "macsetup"
		},
		{
			"path": "npm/devrel"
		},
		{
			"path": "npm/cli"
		},
		{
			"path": "npm/learnyou"
		},
		{
			"path": "npm/help-docs"
		},
		{
			"path": "npm/weallcontribute"
		},
		{
			"path": "npm/alfred-npmjs"
		},
		{
			"path": "others/tab-limiter"
		},
		{
			"path": "chromeextensions"
		},
		{
			"path": "npm/opening-up-npm"
		},
		{
			"path": "ama"
		},
		{
			"path": "others/larch"
		},
		{
			"path": "npm/pacote-fork"
		},
		{
			"path": "gitstuff/git-branch-status"
		},
		{
			"path": "speakerkit"
		},
		{
			"path": "mybusinesscard"
		},
		{
			"path": "chrome/rss-finder"
		},
		{
			"path": "remarkable/rm-dl-annotated"
		},
		{
			"path": "/Users/fharper/Downloads/xochitl"
		}
	],
	"settings": {
		"git.ignoreLimitWarning": true,
		"editor.rulers": [
			80
		],
		"favorites.sortDirection": "ASC",
	}
}
```

**Comment by fharper** [comment]
Oh, I just realized that I was adding the path to the file itself, not the directory in `workspacesort.workspaceDirectory`, my bad! I guess that the code could check if it's a folder before attempting any more actions?

Still, I have the same error. I'll try to check by debugging it.

**Comment by fharper** [comment]
It's definitely something with my `.code-workspace` file as it's working if I create another workspace.

**Comment by iciclesoft** [comment]
> Oh, I just realized that I was adding the path to the file itself, not the directory in `workspacesort.workspaceDirectory`, my bad! I guess that the code could check if it's a folder before attempting any more actions?
> 
> Still, I have the same error. I'll try to check by debugging it.

That is pretty much what it does, if it's a file it will get the directory of the file. This might be a bit redundant though as it still (re)appends the file at a later stage but that's to make it slightly more fool-proof =)

Looking at your `.code-workspace` content, this doesn't show the setting `workspacesort.workspaceDirectory`. Are you sure you don't have 2 `.code-workspace` files, one that's actually used by Visual Studio Code and one that's just lingering? That's currently the only thing I'm noticing that is off.

**Comment by iciclesoft** [comment]
I might've found it, when I try your content on my pc, it crashes on the following:
```
"settings": {
	"git.ignoreLimitWarning": true,
	"editor.rulers": [
		80
	],
	"favorites.sortDirection": "ASC",
}
```
The comma after `"favorites.sortDirection": "ASC",` followed by a `}`. Removing the comma might fix it but I have no idea how it got there, which is a little bit worrying =)

**Comment by fharper** [comment]
Oh, I didn't realize the JSON file wasn't valid. It's weird as I didn't edit that file manually, so it's either when adding or removing an extension (or changing one's setting)... Not good at all, and sorry for the trouble, but maybe it's worth to try/catch the parse function and notify the user if the file isn't valid as I guess I may not be the only one in this position.

Thanks

**Comment by iciclesoft** [comment]
No problem! I'll definitely have a look at notifying the user when the json cannot be parsed.

**Comment by iciclesoft** [comment]
In v1.4.1, a notification is shown whenever the json could not be parsed. I hope this helps if you run into this problem in the future.
