### ISSUE TITLE
not working after i clicked sort

### ISSUE THREAD

**Issue by peterremote1980** [iciclesoft/workspacesort-for-VSCode#3]
Hi, not working after i clicked sort
<img width="1680" alt="screenshot 2019-02-08 at 10 52 47 pm" src="https://user-images.githubusercontent.com/36571333/52485635-4b7cde80-2bf4-11e9-8cf7-2eebab1576c4.png">

**Comment by iciclesoft** [comment]
Hi, do you have some more information? What does it say when you click Sort? Or even better, do you mind sharing the content of your `.code-workspace` file so I can try to reproduce your problem.

**Comment by iciclesoft** [comment]
It seems a change in VSCode might be causing the problem, for this I've created a new issue in the VSCode repository ([see bugreport](https://github.com/Microsoft/vscode/issues/68351)). Can you verify that this is the same problem you are having?

**Comment by iciclesoft** [comment]
@peterremote1980 is this still a problem for you? Otherwise I'll close the issue.

**Comment by iciclesoft** [comment]
The aforementioned bugreport has been fixed in VSCode, the next VSCode release will fix this issue.

**Comment by peterremote1980** [comment]
After i restarted the vscode, it works, thanks for your plugin

**Comment by iciclesoft** [comment]
@peterremote1980 Version 1.32.1 of VSCode contains a fix for this issue. Changes will now take effect immediately and do not require a restart of VSCode.
