### ISSUE TITLE
Plugin seemingly wrecks the built-in VSCode source control panel

### ISSUE THREAD

**Issue by bradisbell** [iciclesoft/workspacesort-for-VSCode#4]
Originally, the source control panel built into VSCode would show all of my projects under one expansion item.  After using the workspace sort plugin, now I have a ton of items all expanded, no scroll bar, and I must click every single project to access one near the bottom of the list.

**Comment by iciclesoft** [comment]
Hi Bradisbell,

I'm not sure if I fully understand your problem and if I do, the things shouldn't be related. The only thing the extension does is change the content of the `.code-workspace` file you have currently opened and selected `Sort Workspace Folders` on, the only change this could mean for the `Source Control Manager` is that it might show this file as being changed. The same thing counts for the scroll bar and the usage of the `Source Control Manager`, my extension has no influence on these either other than making a change to the `.code-workspace` file.

In the latest update, the VSCode-team did make changes to the `Source Control Manager`, which might be the root of your problem:
https://code.visualstudio.com/updates/v1_33#_improved-source-control-view

**Comment by bradisbell** [comment]
Thanks for the link!  I bet that "improved" update is what did it, and I just happened to install your plugin at the same time.  Sorry for the erroneous bug report, and thanks for the information!
