### ISSUE TITLE
WSL Support

### ISSUE THREAD

**Issue by ghmj2417** [iciclesoft/workspacesort-for-VSCode#5]
I am using VSCode with WSL.  When attempting to sort my workspace folders I receive an error that my .code-workspace file cannot be found.  I go ahead and set workspacesort.workspaceDirectory to the directory where my config file is located, for example /home/user/vscode.  However, even after setting that in my config file I continue to receive the error when I try to sort.  I tried to look through the code to figure out what is going on but I am at a loss.

I suppose at this point I should ask, should this extension work with WSL?  I would be more than happy to provide any information you need to support this extension as I definitely need it.

VSCode version: 1.37.1
WorkspaceSort version: 1.5.7

**Comment by iciclesoft** [comment]
Hi @ghmj2417 
The extension is designed to work cross-platform, however I have to admit that it's never tested in your setup. Let me see if I am able to get this setup to work with VirtualBox. In the mean time you might want to try this on an insiders version of VSCode to make sure it's not another extension messing around with the results. This can be downloaded [here](https://code.visualstudio.com/insiders/)

**Comment by ghmj2417** [comment]
Thanks @iciclesoft. I will continue testing to see if I can narrow down the issue.

I only have a couple of extensions enabled for WSL and it would blow my mind if they were interfering with yours. But you never know so I will try to minimize my extensions and test again.

**Comment by iciclesoft** [comment]
Hi @ghmj2417 
Following the manual by Dave Rupert (see link below) I did not have any troubles sorting the workspace-folders. One thing in the manual that did grab my attention was the following:
> Where do my project files live?
> In Windowslandia, that’s: C:\Users\<winusername>\
> In WSL, this maps to: /mnt/c/Users/<winusername>$

This comment made me think I had to use `/mnt/c/...` to point to the code-workspace directory however, it seemed to be the windows-way that did the trick. My code-workspace file currently looks like this:
```
{
	"folders": [
		{
			"path": "..\\NewProject"
		},
		{
			"path": "C:\\Users\\marco\\Documents\\Projects\\Shared"
		},
		{
			"path": "C:\\Users\\marco\\Documents\\Projects\\Common"
		}
	],
	"settings": {
		"workspacesort.workspaceDirectory": "C:\\Users\\marco\\Documents\\Projects\\workspace-files\\"
	}
}
```
Perhaps you can fiddle around with that a little bit?

VSCode WSL Manual: https://daverupert.com/2018/04/developing-on-windows-with-wsl-and-visual-studio-code/

**Comment by ghmj2417** [comment]
I looked at that as well, however all of my project folders and workspace settings are contained within WSL.  They don't live outside of the WSL instance.  (Technically speaking, they do live in a folder that is accessible via Windows, but we aren't supposed to touch it).  Example, my folders live in /home/user/project1, /home/user/project2, /home/user/project3, etc and my workspace setting lives in /home/user/vscode/.  The actual folders and setting file do not live in C:\Users or /mnt/c

**Comment by iciclesoft** [comment]
Perhaps you can point me in the right direction on how you've setup your project?

**Comment by ghmj2417** [comment]
Sure.  When I launch VSCode, I automatically remote connect to my WSL instance which is Ubuntu 18.04.  Now I have VSCode running as though it is in my Ubuntu machine.  The VSCode extension I am using is Remote-WSL.  My workspace folders are my repo projects.  The repos are stored in /home/user/repos.  My workspace settings file is stored in /home/user/vscode.

My workspace file looks something like this:
```
{
	"folders": [
		{
			"path": "/home/user/repos/project1"
		},
		{
			"path": "/home/user/repos/project2"
		},
		{
			"path": "/home/user/repos/devstuff"
		}
	],
	"settings": {
		"workspacesort.workspaceDirectory": "/home/user/vscode"
	}
}
```

**Comment by iciclesoft** [comment]
Hi @ghmj2417 
I've just released a new version that has a fix for WSL. Can you verify that this fix works for you?

**Comment by ghmj2417** [comment]
Success.  Works like a charm.  I didn't even have to add workspacesort.workspaceDirectory.  Thank you very much for fixing this.

**Comment by iciclesoft** [comment]
Perfect, enjoy!
