### ISSUE TITLE
feature request: publish to open-vsx

### ISSUE THREAD

**Issue by sysadmiral** [iciclesoft/workspacesort-for-VSCode#9]
Hi,

Just wondered if you would be willing to accept PR's that would publish this extension to [open-vsx][1] in addition to the MS extension marketplace?

Instructions are [here][2].

Many Thanks,

Amo

[1]: https://open-vsx.org/about
[2]: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

**Comment by sysadmiral** [comment]
A github action to automate the publishing: https://github.com/HaaLeo/publish-vscode-extension#readme

**Comment by iciclesoft** [comment]
Hi @sysadmiral sorry for the late reply. Thanks for notifying me about the open-vsx marketplace, I personally never heard about it. I just published the extension on the marketplace which can be found here: https://open-vsx.org/extension/iciclesoft/workspacesort
